### ISSUE TITLE
Serve più granularità della gestione degli errori

### ISSUE THREAD

**Issue by domingosl** [Growish/gw-api-v2-client#3]
L'errore 400 pur essendo tecnicamente un errore del metodo request, non è corretto chiamarlo requestErr, perché anche un 40X lo è (403, 409, 401, ecc)

https://github.com/Growish/gw-api-v2-client/blob/e7b375564e7d605e17813f241ab4976085110649/index.js#L168

Per questa API serve gestire separatamente 400 e 403 a livello globale (oltre al 401 che già gestisce bene il client).

### Nomi suggeriti
400: **badRequestErr**
403: **unauthorizedErr**

Qualunque altro errore va propagato al app (come fa già adesso)

**Comment by valdo99** [comment]
@domingosl 
non è meglio
403: forbiddenErr
401: unauthorizedErr

**Comment by domingosl** [comment]
@valdo99 certo, ho detto una cazzata, 403 -> forbidden
